### ISSUE TITLE
Refactor wrong imports under components dir

### ISSUE THREAD

**Issue by kabaluyot** [Nuxify/jaks.ts#3]
Basically, imports must be in 'dir level' especially for 'global' related components. 

Instead of the current directory,

components/
 - header/
      - Header.vue
 - footer/
      - Footer.vue
 - index.ts

Please change to:

components/
 - Header.vue
 - Footer.vue
 - index.ts

OR

components/
 - header/
      - Header.vue
      - index.ts
 - footer/
      - Footer.vue
      - index.ts
 - index.ts

With the respective exports

**Comment by rttolipas** [comment]
Right, this is noted.
